version: '3.2'
volumes:
  postgres:
services:
  web:
    build:
      context: ./containers
      dockerfile: web
    depends_on:
      - redis
      - postgresql
    image: pagure-web:latest
    ports:
      - "5000:5000"
    volumes:
      - ../lcl/repos:/repos
      - ../lcl/attachments:/attachments
      - ..:/code:z
    environment:
      - GL_USER=root
      - PYTHONPATH=/code
      - PAGURE_CONFIG=/code/dev/openshift.cfg
  worker:
    build:
      context: ./containers
      dockerfile: worker
    depends_on:
      - redis
      - postgresql
    image: pagure-worker:latest
    volumes:
      - ../lcl/repos:/repos
      - ../lcl/attachments:/attachments:ro
      - ..:/code:z
    environment:
      - PYTHONPATH=/code
      - PAGURE_CONFIG=/code/dev/openshift.cfg
  logcom:
    build:
      context: ./containers
      dockerfile: logcom
    depends_on:
      - redis
      - postgresql
    image: pagure-logcom:latest
    volumes:
      - ../lcl/repos:/repos
      - ../lcl/attachments:/attachments:ro
      - ..:/code:z
    environment:
      - PYTHONPATH=.
      - PAGURE_CONFIG=/code/dev/openshift.cfg
  ev:
    build:
      context: ./containers
      dockerfile: ev
    depends_on:
      - redis
    image: pagure-ev:latest
    ports:
      - "8080:8080"
    volumes:
      - ..:/code:z
    environment:
      - PYTHONPATH=.
      - PAGURE_CONFIG=/code/dev/openshift.cfg
  redis:
    image: redis
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=pagure
      - POSTGRES_PASSWORD=pagure
      - POSTGRES_DB=pagure
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata:z
